#!/usr/bin/env bash
# {{HUB_COMMAND}}: Claude Code through the workshop gateway, on a JupyterHub.
# Generated by scripts/render.py from assets/hub-signup.sh. Do not edit here.
#
#   {{HUB_DIR}}/{{HUB_COMMAND}}          first time (then just: {{HUB_COMMAND}})
#   {{HUB_COMMAND}} --budget             how much of your budget is left
#   {{HUB_COMMAND}} --reset              forget your saved key
#   {{HUB_COMMAND}} --status FILE        organizers: spend of every key in a key file
#
# The first run asks for a workshop code or a key. A code said in the room gets
# you a personal key from the gateway's sign-up; a key (sk-...) handed to you by
# your organizer is checked and used as it is. Either is saved in
# ~/.config/{{HUB_COMMAND}}/key, readable only by you. Claude Code runs with its
# own settings folder, ~/.config/{{HUB_COMMAND}}/claude, so a personal Claude
# login and settings in ~/.claude are never used or changed: `claude` stays yours.
#
# The gateway URL is not in this file (the install's repo may be public). It is
# read from {{HUB_COMMAND}}.url in the same folder as this script.
set -euo pipefail

CMD={{HUB_COMMAND}}
HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
DIR="$HOME/.config/$CMD"  # not XDG_CONFIG_HOME: a hub may point it at a shared /etc path
KEYFILE="$DIR/key"

GATEWAY_URL=""
[ -r "$HERE/$CMD.url" ] && GATEWAY_URL="$(tr -d '[:space:]' < "$HERE/$CMD.url")"
[ -n "$GATEWAY_URL" ] || { echo "$CMD is not set up yet ($CMD.url is missing). Ask your workshop organizer."; exit 1; }

# So that plain `$CMD` works from now on. A new hub account may have no
# startup files, with ~/.local/bin not on its PATH, so add it. Hub terminals
# are often login shells (bash -l), which read the first of these that exists.
if [ ! -e "$HOME/.local/bin/$CMD" ]; then
  mkdir -p "$HOME/.local/bin"
  ln -s "$HERE/$CMD" "$HOME/.local/bin/$CMD"
fi
login_file="$HOME/.profile"
for f in "$HOME/.bash_profile" "$HOME/.bash_login"; do
  [ -e "$f" ] && { login_file="$f"; break; }
done
for f in "$login_file" "$HOME/.bashrc"; do  # .bashrc: for terminals that are not login shells
  if ! grep -qs '# local bin on PATH (workshop gateway)' "$f"; then
    printf '\nexport PATH="$HOME/.local/bin:$PATH"  # local bin on PATH (workshop gateway)\n' >> "$f"
    added=1
  fi
done
[ -n "${added:-}" ] && echo "Set up: in new terminals you can just type $CMD"
export PATH="$HOME/.local/bin:$PATH"  # where Claude Code installs itself

json() {  # json FIELD < response: print one field of a JSON reply
  python3 -c 'import json,sys; print(json.load(sys.stdin).get(sys.argv[1]) or "")' "$1"
}

# Print one line about a key from its /key/info reply (stdin): spend, budget, expiry.
KEY_LINE='
import json, sys
i = json.load(sys.stdin)["info"]
print("spent $%.2f of $%s; expires %s UTC%s" % (i.get("spend") or 0, i.get("max_budget"),
      (i.get("expires") or "never")[:16], "; BLOCKED" if i.get("blocked") else ""))'

case "${1:-}" in
  --reset)
    rm -f "$KEYFILE"
    echo "Forgot your key. Run $CMD again and type a new workshop code or key."
    echo "(To sign up again with the same code, ask your workshop organizer first.)"; exit 0 ;;
  --budget)
    [ -s "$KEYFILE" ] || { echo "No key yet: run $CMD first."; exit 1; }
    info=$(curl -fsS "$GATEWAY_URL/key/info" -H "Authorization: Bearer $(tr -d '[:space:]' < "$KEYFILE")") \
      || { echo "The gateway did not accept your key (expired or stopped?), or could not be reached."; exit 1; }
    python3 -c "$KEY_LINE" <<<"$info"
    exit 0 ;;
  --status)
    # For organizers: a key file from `keys.py batch` has lines "<name> <key>".
    # Each key reports only on itself, so this needs no admin key. Keys are
    # never printed. Stopping a key is for the key issuer (keys.py block).
    file="${2:-}"
    [ -r "$file" ] || { echo "Usage: $CMD --status <key file>"; exit 1; }
    while read -r name key _; do
      case "$name" in ''|'#'*) continue ;; esac
      if info=$(curl -fsS "$GATEWAY_URL/key/info" -H "Authorization: Bearer $key" 2>/dev/null); then
        printf '%-24s %s\n' "$name" "$(python3 -c "$KEY_LINE" <<<"$info")"
      else
        printf '%-24s %s\n' "$name" "not accepted: stopped (blocked or deleted) or expired"
      fi
    done < "$file"
    exit 0 ;;
esac

save_key() {
  mkdir -p "$DIR"
  (umask 077; printf '%s\n' "$1" > "$KEYFILE")
}

if [ ! -s "$KEYFILE" ]; then
  read -rp "Workshop code, or the key you were given: " code || { echo; echo "Nothing entered."; exit 1; }
  code="$(printf '%s' "$code" | tr -d '[:space:]')"
  [ -n "$code" ] || { echo "Nothing entered."; exit 1; }
fi

if [ ! -s "$KEYFILE" ] && [[ "$code" == sk-* ]]; then
  # A key handed out by the organizer: check it before saving it.
  info=$(curl -sS -w '\n%{http_code}' "$GATEWAY_URL/key/info" \
    -H "Authorization: Bearer $code" 2>/dev/null) || info=$'\n000'
  status="${info##*$'\n'}"; info="${info%$'\n'*}"
  case "$status" in
    200) save_key "$code"; echo "Key accepted: $(python3 -c "$KEY_LINE" <<<"$info")." ;;
    000) echo "Could not reach the workshop gateway. Try again, or ask your workshop organizer."; exit 1 ;;
    *)   echo "That key was not accepted. Check it was pasted whole; it may also have expired"
         echo "or been stopped. Ask your workshop organizer."; exit 1 ;;
  esac
elif [ ! -s "$KEYFILE" ]; then
  # A workshop code: sign-up makes a key for this hub user.
  user="${JUPYTERHUB_USER:-}"
  [ -n "$user" ] || read -rp "Your hub username: " user
  reply=$(curl -sS "$GATEWAY_URL/workshop/key" -H 'Content-Type: application/json' \
    -d "$(python3 -c 'import json,sys; print(json.dumps({"code": sys.argv[1], "user": sys.argv[2]}))' "$code" "$user")") \
    || { echo "Could not reach the workshop gateway. Try again, or ask your workshop organizer."; exit 1; }
  key=$(json key <<<"$reply" 2>/dev/null || true)
  if [ -z "$key" ]; then
    echo "$(json error <<<"$reply" 2>/dev/null || echo "Unexpected reply from the gateway.")"
    exit 1
  fi
  save_key "$key"
  echo "Got your key for $user (workshop $(json workshop <<<"$reply")): \$$(json budget <<<"$reply") to spend, expires $(json expires <<<"$reply" | cut -c1-10)."
fi

if ! command -v claude >/dev/null; then
  echo "Installing Claude Code (one time, about a minute)..."
  curl -fsSL https://claude.ai/install.sh | bash >/dev/null
fi

# Settings from other ways of running Claude would bypass the gateway.
unset CLAUDE_CODE_USE_BEDROCK CLAUDE_CODE_USE_VERTEX ANTHROPIC_API_KEY \
      AWS_BEARER_TOKEN_BEDROCK ANTHROPIC_SMALL_FAST_MODEL
export CLAUDE_CONFIG_DIR="$DIR/claude"
export ANTHROPIC_BASE_URL="$GATEWAY_URL"
ANTHROPIC_AUTH_TOKEN="$(tr -d '[:space:]' < "$KEYFILE")"
export ANTHROPIC_AUTH_TOKEN
# Auto mode would otherwise ask Anthropic's server whether this session is
# eligible, which a gateway session is not, and pause on a notice until Enter.
export CLAUDE_CODE_AUTO_MODE_SERVER=0
# The /model picker otherwise lists only Claude Code's built-in tiers; this
# adds every model the gateway lets this key use, from its /v1/models list.
export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY=1
# Claude Code picks models by tier; map every tier to a model the gateway serves.
{{CLAUDE_CODE_EXPORTS}}
exec claude "$@"
